CREATE TABLE Unit (
condoID INTEGER PRIMARY KEY NOT NULL,
SQFT INTEGER NOT NULL,
bedNumbers INTEGER NOT NULL,
bathNumbers INTEGER NOT NULL,
maxCapacity INTEGER NOT NULL,
weeklyRate INTEGER NOT NULL);